# Generated by Django 2.1.5 on 2019-01-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
