# Generated by Django 2.1.5 on 2019-02-05 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_dat', models.DateField(default=datetime.datetime.today)),
                ('slots', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField(default=datetime.datetime.today)),
                ('app_slot', models.IntegerField(default=1)),
                ('app_doct', models.CharField(default='N.A', max_length=50)),
                ('app_pay', models.BooleanField(default=False)),
                ('app_pay_ref', models.CharField(default='N.A', max_length=25)),
                ('app_prob', models.TextField(default='N.A', max_length=400)),
                ('app_pri', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='register',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(default='N.A', max_length=150),
        ),
        migrations.AddField(
            model_name='register',
            name='bio',
            field=models.TextField(default='N.A', max_length=150),
        ),
        migrations.AddField(
            model_name='register',
            name='blood_Group',
            field=models.CharField(default='N.A', max_length=10),
        ),
        migrations.AddField(
            model_name='register',
            name='doB',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='facebook',
            field=models.CharField(default='N.A', max_length=70),
        ),
        migrations.AddField(
            model_name='register',
            name='linkedIn',
            field=models.CharField(default='N.A', max_length=70),
        ),
        migrations.AddField(
            model_name='register',
            name='priv',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='register',
            name='twitter',
            field=models.CharField(default='N.A', max_length=70),
        ),
        migrations.AddField(
            model_name='register',
            name='userName',
            field=models.CharField(default='a', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Register'),
        ),
    ]
