# Generated by Django 2.1.5 on 2019-02-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190205_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoint',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Register'),
        ),
    ]
