# Generated by Django 2.1.5 on 2019-02-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190205_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='app_ref',
        ),
    ]
