# Generated by Django 2.1.5 on 2019-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_appointment_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_status',
            field=models.IntegerField(default=2),
        ),
    ]
